/* src/app/constants.ts */

export enum Categories {
  GENERAL = 'General',
  NETWORKING = 'Networking',
  COMPUTEANDWEB = 'Compute & Web',
  //CONTAINERS = 'Containers',
  DATABASES = 'Databases',
  STORAGE = 'Storage',
  AIANDML = 'AI & ML',
  ANALYTICSANDIOT = 'Analytics & IoT',
  VIRTUALDESKTOP = 'Virtual Desktop',
  DEVTOOLS = 'Dev Tools',
  INTEGRATION = 'Integration',
  MIGRATION = 'Migration',
  MANAGEMENT = 'Management',
  AIOPS_ANALYTICS = 'AIOps/Analytics',
  ARTIFACT_PACKAGE_MANAGEMENT = 'Artifact/Package Management',
  CLOUD = 'Cloud',
  COLLABORATION = 'Collaboration',
  CONFIGURATION_AUTOMATION = 'Configuration Automation',
  CONTAINERS = 'Containers',
  CI = 'Continuous Integration',
  DATABASE_MANAGEMENT = 'Database Management',
  CD = 'Continuous Deployment',
  ENTERPRISE_AGILE_PLANNING = 'Enterprise Agile Planning',
  ISSUE_TRACKING_ITSM = 'Issue Tracking/ITSM',
  RELEASE_MANAGEMENT = 'Release Management',
  SECURITY = 'Security',
  SERVERLESS_PAAS = 'Serverless/PaaS',
  SCM = 'Source Control Management',
  TESTING = 'Testing',
  VALUE_STREAM_MANAGEMENT = 'Value Stream Management'
}
